# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efde68c5eba4b8f5d582b58bfbff5584bdacb6a302645ce3d3aa7404a22f89f9d58474c8f732114061170397e9e8f79b13fe42e3b4ea3e2452764b998c16175c

test:
  secret_key_base: ea49bab7ddb740341bacbafd4de03c8947476d8a39ab2e40e3e22532420ad29a67758e7a4a71b9b2966cef538825447d55862304780aa64d3323cc44d654557a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
